spring:
  rabbitmq:
    port: ${RABBIT_PORT:5672}
    host: ${RABBIT_HOST:localhost}
  flyway.locations: classpath:db/migration/postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/test
    username: test
    password: test
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  profiles:
    active: chaos-monkey

# Włączamy obsługę chaos monkey i pozwalamy na dostęp do endpointów
# kontrolnych (m.in. dla chaos monkey)
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    chaosmonkey:
      enabled: true

# Będziemy się odwoływać do tego portu w testach
server.port: 4321

logging:
  level:
    de.codecentric.spring.boot.chaos.monkey: DEBUG
