version: '3'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.8-27-management-alpine
    ports:
      - 5672:5672

