= FRAUD-DETECTION

== Wymagania biznesowe

Weryfikujemy czy dla danego PESELu osoba jest oszustem czy nie. Sprawdzamy czy nie mamy takiej informacji w bazie danych, a jeśli nie to uruchamiamy weryfikacje oraz odpytujemy bazę BIK.

== Jak to zbudować?

Wymagana jest Java 17.

* Uruchom komendę `./mvnw clean install` żeby uruchomić testy i zbudować paczkę z aplikacją oraz kontener dockerowy.
* Uruchom komendę `./mvnw clean install -Pchaos` żeby uruchomić testy chaosu
* Uruchom komendę `./mvnw clean install -Psonar` żeby uruchomić analizę kodu za pomocą SonarQube
* Uruchom komendę `./mvnw clean install -Pjmeter` żeby uruchomić testy wydajnościowe
* Uruchom komendę `./mvnw clean install -Pmutation` żeby uruchomić testy mutacyjne

== Jak to uruchomić?

Po zbudowaniu paczki możesz uruchomić aplikację poprzez jedną z dwóch możliwości:

* Uruchomienie komendy `java -jar spring/target/*.jar`
** Jeśli do tej komendy dopiszesz `--spring.profiles.active=dev` uruchomisz aplikację w trybie deweloperskim
** Jeśli do tej komendy dopiszesz `--spring.profiles.active=chaos-monkey` uruchomisz aplikację w trybie gotowym do inżynierii chaosu
* Uruchomienie komendy `docker run smarttesting/bik-service`

W jednym i w drugim przypadku potrzebne jest uruchomienie infrastruktury wcześniej. W tym celu należy udać się do folderu `docker` i uruchomić przygotowany tam skrypt Docker Compose poprzez uruchomienie komendy `docker-compose up`  (dodatkowo switch `-d` pozwoli uruchomić kontenery w tle).

== Strategia testowania

Kod zawiera przykłady testów ze wszystkich możliwych poziomów. Nie oznacza to, że każdy możliwy przypadek testowy został rzeczywiście przetestowany. Sugerujemy uczestnikom szkolenia najpierw spróbować napisać testy we własnym zakresie, a istniejące testy traktować jako punkt odniesienia.

**Integracyjne** dla końcówek HTTP i messaging (brak kontraktów dla listenera + klientów http, ponieważ nie mamy dostępu do usług zewnętrznych), ale z **usługami uruchomionymi w kontenerze**. W przypadku używania cachea dopiszemy testy z cachem.

**Testy kontraktowe** dla kontrollera HTTP i messagingu. Proponujemy podpięcie RESTDocs żeby wygenerować **dokumentację** (w innych językach proponujemy ją jakkolwiek opisać np. poprzez Swaggera).

**Testy architektury** - kod z pakietu nie powinien wołać kodu z innego pakietu (`infrastructure` nie powinien wołać `personal` i odwrotnie). Jeśli tak jest to należy wydzielić osobny moduł, który będzie współdzielony.

**Chaos testing** - wymagania:

```
 Hipoteza stanu ustalonego
     POST na URL “/{fraudCheck}”, z peselem osoby nie będącej oszustem, odpowie statusem 401, w ciągu 2000 ms
 Metoda
     Włączamy błędy spowodowane integracją z komponentami typu @Service
 Wycofanie
     Wyłączamy błędy spowodowane integracją z komponentami typu @Service
```

Przy testach musimy inwalidować cache!

**Podpięty sonarqube** i **editorconfig**.

**Dev mode** musi być przygotowany w taki sposób, że można lokalnie uruchomić aplikację bez infrastruktury.

**Testy end to end** zaczynające się od Fraud Verifiera i przechodzące przez BIK Service.

**Testy wydajności** na przykładzie JMeter z dwiema aplikacjami.

== Błędy w kodzie produkcyjnym

Implementacja zawiera błędy, które testy powinny wychwycić (powodzenia w ich szukaniu!).

== Uruchomienie Prometheusa i Grafany

Wartości dodanych przez siebie metryk możesz agregować w Prometheusie i tworzyć dla nich dashboardy w Grafanie. Stworzyliśmy do tego celu demo setup do uruchomienia na dockerze.

Przed rozpoczęciem uruchom aplikacje BIKService i FraudDetection. Wykonaj trochę zapytań do aplikacji FraudDetection korzystając ze skryptów `00-app/00-fraud-detection/src/json/fraud.sh` i `00-app/00-fraud-detection/src/json/positive.sh` (możesz podmienić kilka razy UUID w plikach `00-app/00-fraud-detection/src/json/fraud.json` i `00-app/00-fraud-detection/src/json/positive.json` żeby wykonać więcej weryfikacji - jeżeli UUID jest ten sam, wyciągana jest wartość z bazy danych zamiast przeprowadzania nowej weryfikacji).

Zainstaluj też docker-compose (https://docs.docker.com/compose/cli-command/).

1) Sklonuj repozytorium z setupem docker-compose:
```
git clone git@github.com:OlgaMaciaszek/prometheus.git
```

2) Przejdź na branch `smarttesting`
```
git checkout smarttesting
```

3) Uruchom skrypt ustawiający IP:
```
./scripts/update_prometheus.sh
```

4) Uruchom kontenery
```
./scripts/run.sh
```

6) W przeglądarce uruchom Prometheusa pod `localhost:9090`. Możesz przeglądać metryki i tworzyć do nich grafy.

7) W przeglądarce Grafanę pod `localhost:3000` (użytkownik: `admin`, hasło: `foobar`). Na stronie `localhost:3000/dashboards` głównej znajdziesz linki do przykładowych dashboardów. Wykorzystaj dashboard `FraudDetection` do wykonania zadań związanych z KPI i metrykami (poniżej).

== KPI
// Dodaliśmy metrykę typu `Timer` o nazwie` customer.verification` i wykres `Mean Verification time` w Grafanie; TODO: dodaj więcej KPI
* Średni czas trwania weryfikacji poniżej X



== Metryki
// Dodaliśmy metryki typu `Counter`, nazywające się `fraudcheck.results.failure` i `fraudcheck.results.success`; TODO: wykorzystaj je do utworzenia w grafanie wykresu, który pozwoli Ci monitorować wymaganie poniżej:
* Status odpowiedzi FraudController (z ostatnich 5 minut oczekujemy 95% nie fraudów)
// TODO: dodaj metrykę w kodzie i wykres w Grafanie:
* Liczba klientów na minutę

