server:
  port: 9091

spring:
  application:
    name: loan-orders

logging:
  level:
    org.springframework: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - env
          - metrics
          - prometheus
