spring:
  rabbitmq:
    port: ${RABBIT_PORT:5672}
    host: ${RABBIT_HOST:localhost}
  flyway.locations: classpath:db/migration/postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/test
    username: test
    password: test
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

server.port: 9876
