server.port: 8765
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

logging:
  level:
    pl.smarttesting: DEBUG