= Testy A Design Aplikacji

== Zacznijmy od testu! [01]

=== Kod [09-01-01-spring]

Na slajdzie [Brak przyjemności z testowania] mamy kod z
`05-architecture/05-02-packages/05-02-01-core/src/test/java/pl/smarttesting/lesson1/_01_BadClassTests.java` z metody testowej `should_use_a_lot_of_mocks`.

Najpierw kodujemy w `pl.smarttesting.verifier.tdd._01_AcceptanceTests.java`. Na slajdach będziemy przechodzić linia po linii włącznie z niekompilującym się kodem.

Następnie kod, gdzie tworzymy kontroler, który nic nie robi jest dostępny tu `_02_AcceptanceControllerTests.java`. W tym momencie tworzymy prostą implementację kontrolera, który zwraca `null`.

Potem w `_03_AcceptanceControllerSomethingTests.java` tworzymy klasę `Coś`, która jeszcze nie do końca wiemy, co będzie robiła.

Po tym, jak rozpiszemy sobie co mamy zrobić z naszym klientem, dochodzimy do wniosku, że chcemy zweryfikować oszusta. Zatem tworzymy klasę `FraudVerifier` (widoczna w klasie `_04_FraudVerifierFailingTests.java`), która jeszcze nie ma implementacji.

W `_05_FraudVerifierTests.java` zapisujemy przypadki testowe dla naszej implementacji weryfikacji oszusta. Najpierw chcemy żeby jeden test przeszedł, a potem drugi.

W końcu możemy puścić suitę testów akceptacyjnych `_06_AcceptanceTests.java`, które na szczęście przejdą.

== Piramida testów [02]

=== Kod [09-02-pyramid]

Kod do slajdu dot. tego, czy piramida testów jest zawsze taka sama `PyramidTests.java`. Pokazujemy tu symulacje kontrolera, który przekazuje wywołania do klasy łączącej się z bazą danych.

== Przykłady złych testów [03]

* Brak asercji - Klasa `_01_NoAssertionsTests.java` i zawsze przechodzący test. Pokazujemy problem z ukrywaniem asercji w metodach pomocniczych - czasami metoda jest utworzona, a asercji brakuje.
* Za dużo mocków - Klasa `_02_DoesMockitoWorkTests.java` i operowanie tylko na mockach. De facto nie testujemy nic, poza tym, że framework do mockowania działa.
* Mockowanie wywołań statycznych - Klasa `AppTest` w module `09-03-bad-tests` zawiera klasę `_03_FraudService`, gdzie wykorzystujemy dwie "utility classes" ze statycznymi metodami. Jedna to `StringUtils` pochodząca z biblioteki, druga to nasz własny `DatabaseAccessor`. W teście `should_find_any_empty_name` mockujemy wszystko co się da i w pierwszej kolejności próbujemy ogarnąć mockowanie metody narzędziowej.
* Mockowanie wywołań statycznych c.d. -  Klasa `AppTest` i tym razem bierzemy się za `DatabaseAccessor`. Wiemy już, że raczej nie powinniśmy mockować tego wywołania. Test `should_do_some_work_in_database_when_empty_string_found` pokazuje jak to zrobić odpowiednio.
* Stanowość - Klasa `_04_PotentialFraudServiceTests` pokazuje problemy związane ze stanowością w testach.
* Złe ustawienie wtyczek do testów - moduł `09-03-bad-plugin` klasa `FraudVerifierTst`. Z IDE się wywali, z linii komend nie. `pom.xml` w tym samym module pokazuje przykład poprawnej konfiguracji.

== Praca z zastanym kodem

=== Kod [09-04-legacy]

Klasa `_01_FraudVerifier` widoczna na slajdzie po [Cel pracy ze źle zaprojektowanym kodem].

W pliku `_02_FraudVerifierTests` mamy klasę `_03_DatabaseAccessorImpl`. Na jej podstawie powstał kod na slajdzie po screenshocie 4 000 linii kodu.

Następnie próba napisania testu `should_mark_client_with_debt_as_fraud`.

Czas na szew (seam) - `_04_FakeDatabaseAccessor`. Nadpisujemy problematyczną metodę bez zmiany kodu produkcyjnego i test `should_mark_client_with_debt_as_fraud_with_seam`.

Teraz chcemy dodać nową funkcję systemu do klasy `_05_FraudTaxPenaltyCalculatorImpl`.

Pierwsze podejście z `if/else` w `_06_FraudTaxPenaltyCalculatorImplIfElse`. Problem w tym, że dodajemy nowy kod do nieprzetestowanego.

Wprowadzamy pojęcie Klasy Kiełkowania (Sprout). Czyli za pomocą TDD piszemy nową, przetestowaną klasę, który wywołamy w naszym kodzie legacy (`_07_FraudTaxPenaltyCalculatorImplSprout`). Process TDD widoczny tu `_08_SpecialTaxCalculatorTests`.

Załóżmy, że mamy klasę, która wylicza czy dana osoba jest oszustem lub nie, w zależności od tego, czy posiada dług. By wyciągnąć te informacje, musimy odpytać bazę danych. Akcesor do bazy danych tworzony jest w konstruktorze. Załóżmy, że mamy taką implementację weryfikatora oszustów `_09_FraudVerifierLogicInConstructor` i taką dostępu do bazy danych `_10_DatabaseAccessorImplWithLogicInTheConstructor`. Pierwszą rzeczą, którą możemy zrobić to spróbować w ogóle utworzyć nasz obiekt. Napiszmy test `_02_FraudVerifierTests#should_create_an_instance_of_fraud_verifier`. Test wybuchnie! Co możemy zrobić?

W `_11_FraudVerifierLogicInConstructorExtractLogic` widzimy, że możemy dodać drugi konstruktor obok istniejącego, żeby nie tworzyć problematycznego obiektu w konstruktorze, tylko przekazać już otworzony obiekt przez konstruktor. Teraz, możemy utworzyc mocka problematycznego obiektu i napisać test `_02_FraudVerifierTests#should_mark_client_with_debt_as_fraud_with_a_mock`.

Teraz możemy wprowadzić nowy interfejs `_12_DatabaseAccessor`,  który pokrywa się z już istniejącym kodem. Podmieniamy w konstruktorze `FraudVerifier`a klasę na interfejs (`_13_FraudVerifierWithInterface`). Dzięki temu możemy też stworzyć sztuczną implementację interfejsu `_14_FakeDatabaseAccessorWithInterface`.

Poprzez taką operację jesteśmy w stanie bardzo uprościć nasz test `_02_FraudVerifierTests#should_mark_client_with_debt_as_fraud_with_an_extracted_interface`.

==== Obiektu nie da się łatwo utworzyć

Klasa `_15_FraudVerifierTests`. Zawiera implementację `_16_FraudVerifier` jako przykład implementacji z wieloma zależnościami i dużą liczbą linijek kodu.

Pokazujemy dwa przykłady testów, w których próbujemy odgadnąć, które zależności są wymagane poprzez podstawienie nulla. `_15_FraudVerifierTests#should_calculate_penalty_when_fraud_applies_for_a_loan` nie trafiamy i leci `NullPointerException`. W `_15_FraudVerifierTests#should_mark_client_with_debt_as_fraud` trafiamy i test nam przechodzi. W teście `_15_FraudVerifierTests#should_calculate_penalty_when_fraud_applies_for_a_loan_with_both_deps` przekazujemy brakującą zależność i test przechodzi.

==== Globalne zależności

Klasa `_17_FraudVerifierTests`. W klasie `_18_FraudVerifier` mamy przykład implementacji wołającej singleton `DatabaseAccessorImpl`. Przykład implementacji widać tu `_19_DatabaseAccessorImpl`.

To, co możemy zrobić to dodać statyczny setter do implementacji singletona, pozwalający na nadpisanie globalnej instancji, instancją testową. Przykład `_20_DatabaseAccessorImplWithSetter`. Instancja testowa może wyglądać tak jak `_21_FakeDatabaseAccessor`.

Po każdym teście warto po sobie wyczyścić czyli zresetować wartość do tej produkcyjnej. (`@AfterEach` w teście).
