= 07 Idziemy na produkcję

Tematy omawiane w tej części:

* Monitoring
- zobacz: _Demo użycia Metryk_
* Testy w procesie CI/CD
* Testy regresji
* Testowanie na produkcji
* Wydania vs. wdrożenia
- zobacz: _Demo Feature Toggles_


**Uruchamianie aplikacji i testów**

Moduł składa się z 3 podmodułów:
* 2 "aplikacji biznesowych":
- loan-orders - służy do składania wniosków o udzielenie pożyczki
- fraud-verifier - służy do weryfikacji klientów
* Serwera Eureka służącego za ServiceRegistry (eureka-server)

1. Uruchom MongoDB, np. przy użyciu dockera:

```
docker run -p 27017:27017 mongo
```

2. Uruchom Server Eureka:

```
cd 07-going-to-production/07-eureka-server/
./mvnw clean install
./mvnw spring-boot:run

```

3. Uruchom aplikację Fraud Verifier:

```
cd 07-going-to-production/07-fraud-verifier/
./mvnw clean install
./mvnw spring-boot:run
```

4. Uruchom aplikację Loan Orders:

```
cd 07-going-to-production/07-loan-orders/
./mvnw clean install
./mvnw spring-boot:run

```

Na działającym systemie:

```
cd 07-going-to-production/
```

**Demo Feature Toggles**

1) Uruchom zapytanie `http POST :9091/orders < loanOrder.json` żeby utworzyć nowe zamówienie pożyczki

2) Użyj zwróconego UUID żeby zweryfikować status zamówienia: `http GET :9091/orders/{returned id}` - status będzie miał wartość `VERIFIED`

3) W przeglądarce, uruchom konsolę feature togglz (`localhost:9092/togglz-console`) i przestaw `New Verification Feature` na `enabled`

4) Uruchom ponownie zapytanie `http POST :9091/orders < loanOrder.json` żeby utworzyć nowe zamówienie pożyczki

5) Użyj zwróconego UUID żeby zweryfikować status zamówienia: `http GET :9091/orders/{returned id}` - status będzie miał wartość `REJECTED`

TIP: użycie feature-togglez można sprawdzić w klasach w module `fraud-verifier`: `NewTypeOfVerification.java`, a setup funkcjonalności w: `Features.java` i `FeatureTogglesConfig.java`; dodatkowo, możesz sprawdzić zależności związane z feature-togglz w `pom.xml` oraz ich konfigurację poprzez propertiesy we `fraud-verifier`: `application.yml`.

WARNING: Na potrzeby demo, korzystamy ze `StateRepository` (repozytorium stanów feature toggles) w pamięci.Na produkcji zaleca się wykorzystanie repozytorium bazującego na systemie plików bądź bazie danych (https://www.togglz.org/documentation/repositories.html[dokumentacja]).Ponadto, dostęp do konsoli `togglz-console` nie jest chroniony, podczas gdy na produkcji zazwyczaj dostęp do takiej konsoli będziemy chcieli nadać wyłącznie osobom z uprawnieniami administratora.

**Demo Distributed Tracing**

Dzięki wykorzystaniu biblioteki do instrumentacji śledzenia rozproszonego (w przypadku projektu w Javie jest to `Micrometer Tracing` - możesz sprawdzić zależności w plikach `pom.xml`), logi naszych serwisów zawierają teraz prefix `[serviceId, traceId, spanId]` zawierający id serwisu, `traceId` (jedno id odpowiadające wykonywanej operacji, to samo dla wszystkich serwisów, przez które musimy przejść żeby zrealizować operację) i `spanId` odpowiadające odcinkowi tej operacji zrealizowanemu w konkretnym serwisie.

1) Przejrzyj logi aplikacji `fraud-verifier`.
Zobaczysz tam opisane wyżej prefiksy, np.  `[fraud-verifier,42376342459874ab,47978a41d481a975,true]`.
2) Przejdź do logów aplikacji `loan-orders`.
Zaobserwuj, że dla logów tej samej operacji, `traceId` (w tym przykładzie `42376342459874ab`) będzie takie samo.

TIP: Dzięki zastosowaniu biblioteki do instrumentacji śledzenia rozproszonego, jesteśmy w stanie skorelować logi odpowiadające tej samej operacji we wszystkich serwisach wchodzących w skład naszego systemu.
Dobrym pomysłem jest też wykorzystanie dedykowanych narzędzi (np., https://www.elastic.co/kibana[Kibana]), które pozwalają w łatwy sposób analizować takie logi.
Skorelowane w ten sposób logi, możemy też wykorzystać do analizy czasów oczekiwania (latency), korzystając z narzędzi takich jak https://zipkin.io/[Zipkin].

**Demo z Zipkinem**
Używając Zipkina możesz analizować czasy trwania zapytań i odpowiedzi, i całych operacji w systemie.

1) Uruchom Zipkina:
```
docker run -d -p 9411:9411 openzipkin/zipkin
```

2) Wykonaj trochę zapytań opisanych w sekcji "Demo Feature Toggles"

3) W przeglądarce wejdź na `localhost:9411`. Możesz teraz wyszukiwać spany po `serviceId` (np. `serviceId=loan-orders`), `traceId` i `spanId` i weryfikować jakie operacje były wykonywane w których operacjach, ile trwały, i które z nich powodowały największe opóźnienie.


**Demo użycia metryk**

Ponieważ dodaliśmy do naszych aplikacji `spring-boot-starter-actuator`, otrzymujemy sporą listę metryk dostępnych "out-of-the-box".
Dodatkowo, w aplikacji  `fraud-verifier` w `CustomerVerifier.java` wstrzyknęliśmy beana `meterRegistry` i wykorzystaliśmy go do stworzenia obiektu typu `Timer` (rejestrującego czas jaki zajmuje wykonanie operacji) przypisanego do zmiennej `verifyCustomerTimer`, który wykorzystujemy żeby śledzić czas trwania weryfikacji klienta.

1) Uruchom zapytanie `http localhost:9092/actuator/metrics` żeby przejrzeć listę dostępnych metryk.

2) Uruchom zapytanie `http localhost:9092/actuator/metrics/{nazwa metryki, np. verifyCustomerTimer}` żeby przejrzeć dane dostępne dla wybranej metryki (przed analizą danych warto jest wykonać kilka requestów, np. tych wylistowanych w części "Demo Feture Toggles").

3) Dodawaj własne metryki korzystając z biblioteki `micrometer`.


**Demo dashboardów do metryk w Grafanie**

Wartości dodanych przez siebie metryk możesz agregować w Prometheusie i tworzyć dla nich dashboardy w Grafanie. Stworzyliśmy do tego celu demo setup do uruchomienia na dockerze.

Przed rozpoczęciem, zainstaluje docker-compose (https://docs.docker.com/compose/cli-command/).

1) Sklonuj i otwórz repozytorium z setupem docker-compose:
```
git clone git@github.com:OlgaMaciaszek/prometheus.git
```

2) Przejdź na branch `smarttesting`
```
git checkout smarttesting
```

3) Uruchom skrypt ustawiający IP:
```
./scripts/update_prometheus.sh
```

4) Uruchom kontenery
```
./scripts/run.sh
```

5) Wykonaj trochę zapytań opisanych w sekcji "Demo Feature Toggles"

6) W przeglądarce uruchom Prometheusa pod `localhost:9090`. Możesz przeglądać metryki i tworzyć do nich grafy.

7) W przeglądarce Grafanę pod `localhost:3000` (użytkownik: `admin`, hasło: `foobar`). Na stronie `localhost:3000/dashboards` głównej znajdziesz linki do przykładowych dashboardów. "Demo Dashboard" wykorzystuje metrykę, którą dodaliśmy w kodzie. Możesz tworzyć dashboardy dla dodanych przez siebie metryk.



