INSERT INTO occupation_to_score (ID, OCCUPATION, OCCUPATION_SCORE) VALUES (1, 'PROGRAMMER', 1000);
INSERT INTO occupation_to_score (ID, OCCUPATION, OCCUPATION_SCORE) VALUES (2, 'LAWYER', 500);
INSERT INTO occupation_to_score (ID, OCCUPATION, OCCUPATION_SCORE) VALUES (3, 'DOCTOR', 250);
INSERT INTO occupation_to_score (ID, OCCUPATION, OCCUPATION_SCORE) VALUES (4, 'OTHER', 50);
