= 01.01 Testy jednostkowe

Tematy omawiane w tej części:

* Czemu testy są niezbędne
* Czemu testy są opłacalne
* Jakie zasady powinny spełniać dobre testy
* Jak unikać `false passes`:
   - przykład - suite'a testów zawiera test na przypadek negatywny: `CustomerVerifierTest.shouldFailSimpleVerification`, ale nie zawiera tesów weryfikujących pozytywną weryfikację, przez co testy nie wychwytują, że kod produkcyjny zwraca domyślną wartość i brakuje implementacji logiki biznesowej
   - przykład - test `SimpleVerificationTest.shouldFailSimpleVerificationFalsePass`. Test weryfikuje nie to co trzeba (jakieś pole na obiekcie, zamiast zwracanej wartości), przez co przechodzi, mimo że właściwa implementacja nie została dodana.
* Rodzaje testów
* Struktura testów
  - zobacz np. `NationalIdentificationNumberVerificationTest`
* Konwencje nazewnicze
  - zobacz: `NationalIdentificationNumberVerificationTest`
* Używanie konstruktorów
  - pozwala to między innymi na używanie Test Doubles, zobacz: `TestVerificationService`
* Radzenie sobie z metodami statycznymi:
  - zobacz setup pól klasy testowej w `CustomerVerifierTest`
* Asercje i frameworki do asercji
  - zobacz `AgeVerificationTest`
* Wzorzec AssertObject
 - zobacz `LoanOrderServiceTest`

