server.port: 8765
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  flyway.locations: classpath:db/migration/h2,classpath:db/migration/test
  datasource:
    url: jdbc:h2:mem:my-app
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    pl.smarttesting: DEBUG